In [4]:
import numpy as np 

print("****** np.array_split Usage ******\n")
a = np.array([1,2,3,4,5,6,7,8,9,10])
print("Splitting {} as \n".format(a))
print(np.array_split(a, 3))
print("\n")

print("****** np.column_stack Usage ******\n")
x = np.array([1,2,3])
y = np.array([4,5,6])
z = np.array([7,8,9])
print("Stacking the 3 below \n")
print(x)
print(y)
print(z)
print("\n")
print("Result is \n")
print(np.column_stack((x,y,z)))
print("\n")

print("****** np.concatenate Usage ******\n")
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print("Concatenating the 2 below along the column axis\n")
print(a)
print(b)
print("\n")
print("Result is \n")
print(np.concatenate((a, b), axis=0))
print("\n")

print("****** np.hsplit Usage ******\n")
x = np.arange(16.0).reshape(4, 4)
print("Making 2 Horizontal splits(column wise) of below array \n")
print(x)
print("\n")
print("Result is \n")
print(np.hsplit(x, 2))
print("\n")

print("****** np.hstack Usage ******\n")
a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[6]])
print("Stacking the below 2 horizontally (column wise) \n")
print(a)
print(b)
print("\n")
print("Result is \n")
print(np.hstack((a,b)))
print("\n")


print("****** np.squeeze Usage ******\n")
x = np.array([[[0], [1], [2]]])
x = np.array([[[0], [1], [2]],[[3],[4],[5]]])
print("Before Squeezing \n")
print("x : {}\n".format(x))
print("Shape of x : {}".format(x.shape))
print("\n")
print("After squeezing \n")
print("x : {}\n".format(np.squeeze(x)))
print("Shape of x : {}".format(np.squeeze(x).shape))
print("\n")

print("****** np.vsplit Usage ******\n")
x = np.arange(16.0).reshape(4, 4)
print("Making 2 Vertical splits(row wise) of below array \n")
print(x)
print("\n")
print("Result is \n")
print(np.vsplit(x, 2))
print("\n")

print("****** np.vstack Usage ******\n")
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])
print("Stacking the below 2 vertically (row wise) \n")
print(a)
print(b)
print("\n")
print("Result is \n")
print(np.vstack((a,b)))
print("\n")


****** np.array_split Usage ******

Splitting [ 1  2  3  4  5  6  7  8  9 10] as 

[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]


****** np.column_stack Usage ******

Stacking the 3 below 

[1 2 3]
[4 5 6]
[7 8 9]


Result is 

[[1 4 7]
 [2 5 8]
 [3 6 9]]


****** np.concatenate Usage ******

Concatenating the 2 below along the column axis

[[1 2]
 [3 4]]
[[5 6]]


Result is 

[[1 2]
 [3 4]
 [5 6]]


****** np.hsplit Usage ******

Making 2 Horizontal splits(column wise) of below array 

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


Result is 

[array([[ 0.,  1.],
       [ 4.,  5.],
       [ 8.,  9.],
       [12., 13.]]), array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.],
       [14., 15.]])]


****** np.hstack Usage ******

Stacking the below 2 horizontally (column wise) 

[[1]
 [2]
 [3]]
[[4]
 [5]
 [6]]


Result is 

[[1 4]
 [2 5]
 [3 6]]


****** np.squeeze Usage ******

Before Squeezing 

x : [[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5

In [5]:
a = np.array([[1],[2],[3]])
np.shape(a)

(3, 1)

In [6]:
a = np.array([1,2,3])
np.shape(a)

(3,)

In [7]:
import numpy as np 

a = np.arange(6).reshape(2,3) + 10
print("The numpy array is \n")
print(a)
print("\n")

print("****** np.argmax Usage ******\n")
print("The index of maximum value from the flattened version is \n")
print(np.argmax(a))
print("\n")

print("The indices of maximum values along the column are \n")
print(np.argmax(a, axis=0))
print("\n")

print("The indices of maximum values along the row are \n")
print(np.argmax(a, axis=1))
print("\n")



print("****** np.argmin Usage ******\n")

print("The index of minimum value from the flattened version is \n")
print(np.argmin(a))
print("\n")

print("The indices of minimum values along the column are \n")
print(np.argmin(a, axis=0))
print("\n")

print("The indices of minimum values along the row are \n")
print(np.argmin(a, axis=1))
print("\n")


print("****** np.sort Usage ******\n")

b = np.array([[1,4],[3,1]])
print("Numpy array before applying the sorting operation \n")
print(b)
print("\n")
print("The result of sorting along the last axis \n")
print(np.sort(b))
print("\n")

print("The result of sorting the flattened version of the array \n")
print(np.sort(b, axis=None))
print("\n")

print("The result of sorting along the first axis \n")
print(np.sort(b, axis=0))
print("\n")


The numpy array is 

[[10 11 12]
 [13 14 15]]


****** np.argmax Usage ******

The index of maximum value from the flattened version is 

5


The indices of maximum values along the column are 

[1 1 1]


The indices of maximum values along the row are 

[2 2]


****** np.argmin Usage ******

The index of minimum value from the flattened version is 

0


The indices of minimum values along the column are 

[0 0 0]


The indices of minimum values along the row are 

[0 0]


****** np.sort Usage ******

Numpy array before applying the sorting operation 

[[1 4]
 [3 1]]


The result of sorting along the last axis 

[[1 4]
 [1 3]]


The result of sorting the flattened version of the array 

[1 1 3 4]


The result of sorting along the first axis 

[[1 1]
 [3 4]]


